### ISSUE TITLE
シミュレータを書く

### ISSUE THREAD

**Issue by mdj982** [Adelie-project/CPU-Adelie#2]

**Comment by mdj982** [comment]
どうせ逆アセンブルすると思うので、アセンブラもついでに書きます。

**Comment by yamaguchi1024** [comment]
決めていいよ、もしくはコンパイラと話し合って決めていいんじゃない(intel記法でレジスタはr10とかの表記がいいな、即値にはとりあえず$つけるか)

**Comment by mdj982** [comment]
わかった、ありがとう
